/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Upsell3RouteImport } from './routes/upsell-3'
import { Route as Upsell2RouteImport } from './routes/upsell-2'
import { Route as Upsell1RouteImport } from './routes/upsell-1'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ScratchRouteImport } from './routes/scratch'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AlmostThereRouteImport } from './routes/almost-there'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIdRouteImport } from './routes/portal.$id'
import { Route as ListenIdRouteImport } from './routes/listen.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiAdminIpCheckRouteImport } from './routes/api.admin.ip-check'
import { Route as ApiAdminIpAddRouteImport } from './routes/api.admin.ip-add'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const Upsell3Route = Upsell3RouteImport.update({
  id: '/upsell-3',
  path: '/upsell-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell2Route = Upsell2RouteImport.update({
  id: '/upsell-2',
  path: '/upsell-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell1Route = Upsell1RouteImport.update({
  id: '/upsell-1',
  path: '/upsell-1',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ScratchRoute = ScratchRouteImport.update({
  id: '/scratch',
  path: '/scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmostThereRoute = AlmostThereRouteImport.update({
  id: '/almost-there',
  path: '/almost-there',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIdRoute = PortalIdRouteImport.update({
  id: '/portal/$id',
  path: '/portal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenIdRoute = ListenIdRouteImport.update({
  id: '/listen/$id',
  path: '/listen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminIpCheckRoute = ApiAdminIpCheckRouteImport.update({
  id: '/api/admin/ip-check',
  path: '/api/admin/ip-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIpAddRoute = ApiAdminIpAddRouteImport.update({
  id: '/api/admin/ip-add',
  path: '/api/admin/ip-add',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/almost-there': typeof AlmostThereRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/processing': typeof ProcessingRoute
  '/scratch': typeof ScratchRoute
  '/terms': typeof TermsRoute
  '/upsell-1': typeof Upsell1Route
  '/upsell-2': typeof Upsell2Route
  '/upsell-3': typeof Upsell3Route
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/listen/$id': typeof ListenIdRoute
  '/portal/$id': typeof PortalIdRoute
  '/api/admin/ip-add': typeof ApiAdminIpAddRoute
  '/api/admin/ip-check': typeof ApiAdminIpCheckRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/almost-there': typeof AlmostThereRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/processing': typeof ProcessingRoute
  '/scratch': typeof ScratchRoute
  '/terms': typeof TermsRoute
  '/upsell-1': typeof Upsell1Route
  '/upsell-2': typeof Upsell2Route
  '/upsell-3': typeof Upsell3Route
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/listen/$id': typeof ListenIdRoute
  '/portal/$id': typeof PortalIdRoute
  '/api/admin/ip-add': typeof ApiAdminIpAddRoute
  '/api/admin/ip-check': typeof ApiAdminIpCheckRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/almost-there': typeof AlmostThereRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/processing': typeof ProcessingRoute
  '/scratch': typeof ScratchRoute
  '/terms': typeof TermsRoute
  '/upsell-1': typeof Upsell1Route
  '/upsell-2': typeof Upsell2Route
  '/upsell-3': typeof Upsell3Route
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/listen/$id': typeof ListenIdRoute
  '/portal/$id': typeof PortalIdRoute
  '/api/admin/ip-add': typeof ApiAdminIpAddRoute
  '/api/admin/ip-check': typeof ApiAdminIpCheckRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/almost-there'
    | '/checkout'
    | '/create'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/processing'
    | '/scratch'
    | '/terms'
    | '/upsell-1'
    | '/upsell-2'
    | '/upsell-3'
    | '/admin/login'
    | '/auth/callback'
    | '/checkout/return'
    | '/listen/$id'
    | '/portal/$id'
    | '/api/admin/ip-add'
    | '/api/admin/ip-check'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/almost-there'
    | '/checkout'
    | '/create'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/processing'
    | '/scratch'
    | '/terms'
    | '/upsell-1'
    | '/upsell-2'
    | '/upsell-3'
    | '/admin/login'
    | '/auth/callback'
    | '/checkout/return'
    | '/listen/$id'
    | '/portal/$id'
    | '/api/admin/ip-add'
    | '/api/admin/ip-check'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/almost-there'
    | '/checkout'
    | '/create'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/processing'
    | '/scratch'
    | '/terms'
    | '/upsell-1'
    | '/upsell-2'
    | '/upsell-3'
    | '/admin/login'
    | '/auth/callback'
    | '/checkout/return'
    | '/listen/$id'
    | '/portal/$id'
    | '/api/admin/ip-add'
    | '/api/admin/ip-check'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlmostThereRoute: typeof AlmostThereRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessingRoute: typeof ProcessingRoute
  ScratchRoute: typeof ScratchRoute
  TermsRoute: typeof TermsRoute
  Upsell1Route: typeof Upsell1Route
  Upsell2Route: typeof Upsell2Route
  Upsell3Route: typeof Upsell3Route
  AuthCallbackRoute: typeof AuthCallbackRoute
  ListenIdRoute: typeof ListenIdRoute
  PortalIdRoute: typeof PortalIdRoute
  ApiAdminIpAddRoute: typeof ApiAdminIpAddRoute
  ApiAdminIpCheckRoute: typeof ApiAdminIpCheckRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upsell-3': {
      id: '/upsell-3'
      path: '/upsell-3'
      fullPath: '/upsell-3'
      preLoaderRoute: typeof Upsell3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-2': {
      id: '/upsell-2'
      path: '/upsell-2'
      fullPath: '/upsell-2'
      preLoaderRoute: typeof Upsell2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-1': {
      id: '/upsell-1'
      path: '/upsell-1'
      fullPath: '/upsell-1'
      preLoaderRoute: typeof Upsell1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scratch': {
      id: '/scratch'
      path: '/scratch'
      fullPath: '/scratch'
      preLoaderRoute: typeof ScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almost-there': {
      id: '/almost-there'
      path: '/almost-there'
      fullPath: '/almost-there'
      preLoaderRoute: typeof AlmostThereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$id': {
      id: '/portal/$id'
      path: '/portal/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof PortalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen/$id': {
      id: '/listen/$id'
      path: '/listen/$id'
      fullPath: '/listen/$id'
      preLoaderRoute: typeof ListenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/ip-check': {
      id: '/api/admin/ip-check'
      path: '/api/admin/ip-check'
      fullPath: '/api/admin/ip-check'
      preLoaderRoute: typeof ApiAdminIpCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ip-add': {
      id: '/api/admin/ip-add'
      path: '/api/admin/ip-add'
      fullPath: '/api/admin/ip-add'
      preLoaderRoute: typeof ApiAdminIpAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AlmostThereRoute: AlmostThereRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessingRoute: ProcessingRoute,
  ScratchRoute: ScratchRoute,
  TermsRoute: TermsRoute,
  Upsell1Route: Upsell1Route,
  Upsell2Route: Upsell2Route,
  Upsell3Route: Upsell3Route,
  AuthCallbackRoute: AuthCallbackRoute,
  ListenIdRoute: ListenIdRoute,
  PortalIdRoute: PortalIdRoute,
  ApiAdminIpAddRoute: ApiAdminIpAddRoute,
  ApiAdminIpCheckRoute: ApiAdminIpCheckRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
